/** Constants in here */
export const CONTEXT = 'APP/CONTAINERS/HOMEPAGE';

export const FETCH_HOME_DATA_REQUEST = `${CONTEXT}/FETCH_HOME_DATA_REQUEST`;
export const FETCH_HOME_DATA_SUCCESS = `${CONTEXT}/FETCH_HOME_DATA_SUCCESS`;
export const FETCH_HOME_DATA_FAILURE = `${CONTEXT}/FETCH_HOME_DATA_FAILURE`;
